services:
  # _defaults:
  #   autowire: true      # Automatically injects dependencies in your services.
  #   autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  #   public: false       # Allows optimizing the container by removing unused services; this also means

  # SeoBundle\:
  #   resource: '../../*'
  #   exclude: '../../{DependencyInjection,Entity,Migrations,Model,Resources,Tests}'

  # seo_bundle.delete.listener:
  #   class: SeoBundle\EventListener\FileDeleteListener
  #   tags:
  #     - { name: doctrine.event_listener, event: preRemove }

  # seo_bundle.update.listener:
  #   class: SeoBundle\EventListener\FileUpdateListener
  #   tags:
  #     - { name: doctrine.event_listener, event: preUpdate }

    Ocd\NewsBundle\Provider\NewsProvider:
        public: true
        arguments: ['@Ocd\NewsBundle\Repository\NewsRepository','@Ocd\NewsBundle\Provider\NewsTagProvider']

    Ocd\NewsBundle\Provider\NewsTagProvider:
        public: true
        arguments: ['@Ocd\NewsBundle\Repository\NewsTagRepository']

    Ocd\NewsBundle\Repository\NewsRepository:
        public: true
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    Ocd\NewsBundle\Repository\NewsTagRepository:
        public: true
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    Ocd\NewsBundle\Repository\NewsLinkRepository:
        public: true
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    Ocd\NewsBundle\Repository\NewsAttachmentRepository:
        public: true
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    Ocd\NewsBundle\Controller\NewsController:
        public: true
        tags: ['controller.service_arguments']
        arguments: ['@Ocd\NewsBundle\Provider\NewsProvider','@Ocd\NewsBundle\Provider\NewsTagProvider']
 
    ocd_news.directory_namer:
        class: Ocd\NewsBundle\Services\NewsDirectoryNamer
        public: true










